Update Jenkins-ci

diff --git a/Jenkins-ci b/Jenkins-ci
--- a/Jenkins-ci
+++ b/Jenkins-ci
@@ -3,6 +3,7 @@ pipeline {
     environment {
         REPO_URL = "git@github.com:basmaoueslati/trainingTests.git"  
         BRANCH_NAME = "main"  // Update to your branch
+        ip_docker="35.180.232.17"
     }
     stages {
 
@@ -108,26 +109,26 @@ pipeline {
             steps {
                 echo '___Cleaning up old Docker images on remote server___'
                 sh '''
-                IMAGE_IDS=$(docker -H ssh://ubuntu@35.180.232.17 images --filter=reference='basmaoueslati/compare-appf25*' --format '{{.ID}}')
+                IMAGE_IDS=$(docker -H ssh://ubuntu@${ip_docker} images --filter=reference='basmaoueslati/compare-appf25*' --format '{{.ID}}')
         
                 for IMAGE_ID in $IMAGE_IDS; do
                     echo "Processing image ID: $IMAGE_ID"
         
                     # Get containers based on the image
-                    CONTAINERS=$(docker -H ssh://ubuntu@35.180.232.17 ps -a -q --filter ancestor=$IMAGE_ID)
+                    CONTAINERS=$(docker -H ssh://ubuntu@${ip_docker} ps -a -q --filter ancestor=$IMAGE_ID)
         
                     if [ -n "$CONTAINERS" ]; then
                         echo "Stopping and removing containers using image $IMAGE_ID"
-                        docker -H ssh://ubuntu@35.180.232.17 rm -f $CONTAINERS
+                        docker -H ssh://ubuntu@${ip_docker} rm -f $CONTAINERS
                     fi
         
                     # Attempt to remove the image
                     echo "Removing image $IMAGE_ID"
-                    docker -H ssh://ubuntu@13.38.26.14 rmi -f $IMAGE_ID || echo "Could not remove image $IMAGE_ID"
+                    docker -H ssh://ubuntu@${ip_docker} rmi -f $IMAGE_ID || echo "Could not remove image $IMAGE_ID"
                 done
         
                 echo "Pruning dangling images"
-                docker -H ssh://ubuntu@35.180.232.17 image prune -f
+                docker -H ssh://ubuntu@${ip_docker} image prune -f
                 '''
             }
         }
@@ -135,8 +136,8 @@ pipeline {
             steps {
                 echo 'Removing old container "myapp" on remote server if it exists...'
                 sh '''
-                docker -H ssh://ubuntu@35.180.232.17 ps -a -q -f name=myapp | grep . && \
-                docker -H ssh://ubuntu@35.180.232.17 rm -f myapp || echo "Container does not exist."
+                docker -H ssh://ubuntu@${ip_docker} ps -a -q -f name=myapp | grep . && \
+                docker -H ssh://ubuntu@${ip_docker} rm -f myapp || echo "Container does not exist."
                 '''
             }
         }
@@ -146,7 +147,7 @@ pipeline {
         script {
             def version = NEXT_VERSION      
             sh """
-            docker -H ssh://ubuntu@35.180.232.17 run -d --name myapp -p 8086:8080 basmaoueslati/compare-appf25:${version}
+            docker -H ssh://ubuntu@${ip_docker} run -d --name myapp -p 8086:8080 basmaoueslati/compare-appf25:${version}
             """
         }
             }  
